pipeline:
    name: Pipeline
    identifier: Pipeline
    projectIdentifier: Harnesspoc
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: denesh
                repoName: Dronedotnet
                build: <+input>
    stages:
        - stage:
              name: stagebuild
              identifier: stagebuild
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: Cluster
                          namespace: default
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: Docker
                                    image: mcr.microsoft.com/dotnet/samples:aspnetapp
                                    command: ls
                                when:
                                    stageStatus: All
                                failureStrategies: []
