pipeline:
    name: project6
    identifier: project6
    projectIdentifier: Harnesspoc
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stage6
              identifier: stage6
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: Nodes
                          namespace: default
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: six
                                identifier: six
                                spec:
                                    connectorRef: Docker
                                    image: maven:latest
                                    command: |-
                                        ls
                                        mvn -v
